sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
	- "8"
notifications:
  email: false
before_script:
  - npm prune
script:
  - yarn lint && yarn test
after_success:
  - yarn semantic-release
